"""initial schema

Revision ID: 20260811_0001
Revises:
Create Date: 2026-08-11 08:24:54.166406
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260811_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("sreality_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Enum("chata", "chalupa", name="listing_kind"), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inactive_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_price_czk", sa.BigInteger(), nullable=True),
        sa.Column("price_czk", sa.BigInteger(), nullable=True),
        sa.Column("price_on_request", sa.Boolean(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("source_price_per_sqm_czk", sa.BigInteger(), nullable=True),
        sa.Column("derived_price_per_sqm_czk", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_note", sa.Text(), nullable=True),
        sa.Column("locality_text", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column("municipality", sa.Text(), nullable=True),
        sa.Column("region_source_id", sa.BigInteger(), nullable=True),
        sa.Column("district_source_id", sa.BigInteger(), nullable=True),
        sa.Column("municipality_source_id", sa.BigInteger(), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("location_inaccuracy", sa.String(length=80), nullable=True),
        sa.Column("usable_area_m2", sa.Integer(), nullable=True),
        sa.Column("land_area_m2", sa.Integer(), nullable=True),
        sa.Column("building_area_m2", sa.Integer(), nullable=True),
        sa.Column("floor_area_m2", sa.Integer(), nullable=True),
        sa.Column("garden_area_m2", sa.Integer(), nullable=True),
        sa.Column("building_condition_code", sa.Integer(), nullable=True),
        sa.Column("building_type_code", sa.Integer(), nullable=True),
        sa.Column("object_type_code", sa.Integer(), nullable=True),
        sa.Column("room_count_code", sa.Integer(), nullable=True),
        sa.Column("energy_rating_code", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("detail_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("params_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_extra_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_active AND inactive_at IS NULL) OR (NOT is_active AND inactive_at IS NOT NULL)",
            name=op.f("ck_listings_active_matches_inactive_at"),
        ),
        sa.CheckConstraint(
            "(latitude IS NULL) = (longitude IS NULL)",
            name=op.f("ck_listings_coordinates_both_or_neither"),
        ),
        sa.CheckConstraint(
            "NOT price_on_request OR price_czk IS NULL",
            name=op.f("ck_listings_on_request_has_no_price"),
        ),
        sa.CheckConstraint(
            "building_area_m2 IS NULL OR building_area_m2 >= 0",
            name=op.f("ck_listings_building_area_nonnegative"),
        ),
        sa.CheckConstraint(
            "derived_price_per_sqm_czk IS NULL OR derived_price_per_sqm_czk >= 0",
            name=op.f("ck_listings_derived_price_per_sqm_nonnegative"),
        ),
        sa.CheckConstraint(
            "detail_changed_at >= first_seen_at",
            name=op.f("ck_listings_detail_change_after_first_seen"),
        ),
        sa.CheckConstraint(
            "first_seen_at <= last_seen_at", name=op.f("ck_listings_seen_times_ordered")
        ),
        sa.CheckConstraint(
            "floor_area_m2 IS NULL OR floor_area_m2 >= 0",
            name=op.f("ck_listings_floor_area_nonnegative"),
        ),
        sa.CheckConstraint(
            "garden_area_m2 IS NULL OR garden_area_m2 >= 0",
            name=op.f("ck_listings_garden_area_nonnegative"),
        ),
        sa.CheckConstraint(
            "land_area_m2 IS NULL OR land_area_m2 >= 0",
            name=op.f("ck_listings_land_area_nonnegative"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90",
            name=op.f("ck_listings_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name=op.f("ck_listings_longitude_range"),
        ),
        sa.CheckConstraint(
            "price_czk IS NULL OR price_czk >= 0", name=op.f("ck_listings_price_nonnegative")
        ),
        sa.CheckConstraint(
            "source_price_czk IS DISTINCT FROM 0 OR (price_czk IS NULL AND price_on_request)",
            name=op.f("ck_listings_zero_price_is_on_request"),
        ),
        sa.CheckConstraint(
            "source_price_czk IS NULL OR source_price_czk >= 0",
            name=op.f("ck_listings_source_price_nonnegative"),
        ),
        sa.CheckConstraint(
            "usable_area_m2 IS NULL OR usable_area_m2 >= 0",
            name=op.f("ck_listings_usable_area_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint("sreality_id", name=op.f("uq_listings_sreality_id")),
    )
    op.create_index(
        "ix_listings_active_derived_price_per_sqm",
        "listings",
        ["derived_price_per_sqm_czk"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_listings_active_kind_region_district",
        "listings",
        ["kind", "region", "district"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_listings_active_land_area",
        "listings",
        ["land_area_m2"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_listings_active_last_seen",
        "listings",
        ["is_active", sa.literal_column("last_seen_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_listings_active_price",
        "listings",
        ["price_czk"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_listings_active_usable_area",
        "listings",
        ["usable_area_m2"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("logical_key", sa.String(length=160), nullable=False),
        sa.Column(
            "trigger", sa.Enum("scheduled", "manual", name="scrape_run_trigger"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("running", "succeeded", "partial", "failed", name="scrape_run_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chata_complete", sa.Boolean(), nullable=False),
        sa.Column("chalupa_complete", sa.Boolean(), nullable=False),
        sa.Column("found_count", sa.Integer(), nullable=False),
        sa.Column("new_count", sa.Integer(), nullable=False),
        sa.Column("changed_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("deactivated_count", sa.Integer(), nullable=False),
        sa.Column("scraper_version", sa.String(length=64), nullable=False),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status <> 'succeeded' OR "
            "(finished_at IS NOT NULL AND chata_complete AND chalupa_complete)",
            name=op.f("ck_scrape_runs_succeeded_is_complete"),
        ),
        sa.CheckConstraint(
            "changed_count >= 0", name=op.f("ck_scrape_runs_changed_count_nonnegative")
        ),
        sa.CheckConstraint(
            "deactivated_count >= 0", name=op.f("ck_scrape_runs_deactivated_count_nonnegative")
        ),
        sa.CheckConstraint("error_count >= 0", name=op.f("ck_scrape_runs_error_count_nonnegative")),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_scrape_runs_valid_times"),
        ),
        sa.CheckConstraint("found_count >= 0", name=op.f("ck_scrape_runs_found_count_nonnegative")),
        sa.CheckConstraint("new_count >= 0", name=op.f("ck_scrape_runs_new_count_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scrape_runs")),
        sa.UniqueConstraint("logical_key", name=op.f("uq_scrape_runs_logical_key")),
    )
    op.create_index(
        "ix_scrape_runs_started_at",
        "scrape_runs",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_scrape_runs_status_started_at",
        "scrape_runs",
        ["status", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "listing_distances",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("reference_key", sa.String(length=80), nullable=False),
        sa.Column("reference_version", sa.Integer(), nullable=False),
        sa.Column("coordinate_hash", sa.String(length=64), nullable=False),
        sa.Column("target_latitude", sa.Double(), nullable=False),
        sa.Column("target_longitude", sa.Double(), nullable=False),
        sa.Column("air_distance_km", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("road_distance_km", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("drive_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("travel_mode", sa.String(length=32), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "air_distance_km IS NULL OR air_distance_km >= 0",
            name=op.f("ck_listing_distances_air_distance_nonnegative"),
        ),
        sa.CheckConstraint(
            "drive_duration_minutes IS NULL OR drive_duration_minutes >= 0",
            name=op.f("ck_listing_distances_duration_nonnegative"),
        ),
        sa.CheckConstraint(
            "reference_version > 0", name=op.f("ck_listing_distances_reference_version_positive")
        ),
        sa.CheckConstraint(
            "road_distance_km IS NULL OR road_distance_km >= 0",
            name=op.f("ck_listing_distances_road_distance_nonnegative"),
        ),
        sa.CheckConstraint(
            "target_latitude BETWEEN -90 AND 90",
            name=op.f("ck_listing_distances_target_latitude_range"),
        ),
        sa.CheckConstraint(
            "target_longitude BETWEEN -180 AND 180",
            name=op.f("ck_listing_distances_target_longitude_range"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_distances_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_distances")),
        sa.UniqueConstraint(
            "listing_id",
            "reference_key",
            "reference_version",
            "coordinate_hash",
            "provider",
            "travel_mode",
            name=op.f(
                "uq_listing_distances_listing_id_reference_key_reference_version_coordinate_hash_provider_travel_mode"
            ),
        ),
    )
    op.create_index(
        "ix_listing_distances_listing_calculated",
        "listing_distances",
        ["listing_id", sa.literal_column("calculated_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_listing_distances_reference_road",
        "listing_distances",
        ["reference_key", "reference_version", "road_distance_km"],
        unique=False,
    )
    op.create_table(
        "listing_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "price_decreased",
                "price_increased",
                "details_changed",
                "deactivated",
                "reactivated",
                name="listing_event_type",
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("old_price_czk", sa.BigInteger(), nullable=True),
        sa.Column("new_price_czk", sa.BigInteger(), nullable=True),
        sa.Column("changes_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "new_price_czk IS NULL OR new_price_czk >= 0",
            name=op.f("ck_listing_events_new_price_nonnegative"),
        ),
        sa.CheckConstraint(
            "old_price_czk IS NULL OR old_price_czk >= 0",
            name=op.f("ck_listing_events_old_price_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_events_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scrape_runs.id"],
            name=op.f("fk_listing_events_run_id_scrape_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_events")),
        sa.UniqueConstraint(
            "run_id",
            "listing_id",
            "event_type",
            name=op.f("uq_listing_events_run_id_listing_id_event_type"),
        ),
    )
    op.create_index(
        "ix_listing_events_listing_occurred",
        "listing_events",
        ["listing_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_listing_events_type_occurred",
        "listing_events",
        ["event_type", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "listing_images",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("source_image_id", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archive_object_key", sa.Text(), nullable=True),
        sa.Column(
            "archive_status",
            sa.Enum("source_only", "pending", "archived", "failed", name="image_archive_status"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "first_seen_at <= last_seen_at", name=op.f("ck_listing_images_seen_times_ordered")
        ),
        sa.CheckConstraint(
            "height IS NULL OR height > 0", name=op.f("ck_listing_images_height_positive")
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_listing_images_position_nonnegative")),
        sa.CheckConstraint(
            "width IS NULL OR width > 0", name=op.f("ck_listing_images_width_positive")
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_images_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_images")),
        sa.UniqueConstraint(
            "listing_id",
            "source_fingerprint",
            name=op.f("uq_listing_images_listing_id_source_fingerprint"),
        ),
    )
    op.create_index(
        "ix_listing_images_listing_position",
        "listing_images",
        ["listing_id", "position"],
        unique=False,
    )
    op.create_table(
        "listing_observations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_price_czk", sa.BigInteger(), nullable=True),
        sa.Column("price_czk", sa.BigInteger(), nullable=True),
        sa.Column("price_on_request", sa.Boolean(), nullable=False),
        sa.Column("usable_area_m2", sa.Integer(), nullable=True),
        sa.Column("land_area_m2", sa.Integer(), nullable=True),
        sa.Column("building_area_m2", sa.Integer(), nullable=True),
        sa.Column("derived_price_per_sqm_czk", sa.BigInteger(), nullable=True),
        sa.Column("detail_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_object_key", sa.Text(), nullable=True),
        sa.Column("snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "NOT price_on_request OR price_czk IS NULL",
            name=op.f("ck_listing_observations_on_request_has_no_price"),
        ),
        sa.CheckConstraint(
            "building_area_m2 IS NULL OR building_area_m2 >= 0",
            name=op.f("ck_listing_observations_building_area_nonnegative"),
        ),
        sa.CheckConstraint(
            "derived_price_per_sqm_czk IS NULL OR derived_price_per_sqm_czk >= 0",
            name=op.f("ck_listing_observations_derived_price_per_sqm_nonnegative"),
        ),
        sa.CheckConstraint(
            "land_area_m2 IS NULL OR land_area_m2 >= 0",
            name=op.f("ck_listing_observations_land_area_nonnegative"),
        ),
        sa.CheckConstraint(
            "price_czk IS NULL OR price_czk >= 0",
            name=op.f("ck_listing_observations_price_nonnegative"),
        ),
        sa.CheckConstraint(
            "source_price_czk IS NULL OR source_price_czk >= 0",
            name=op.f("ck_listing_observations_source_price_nonnegative"),
        ),
        sa.CheckConstraint(
            "usable_area_m2 IS NULL OR usable_area_m2 >= 0",
            name=op.f("ck_listing_observations_usable_area_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_observations_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scrape_runs.id"],
            name=op.f("fk_listing_observations_run_id_scrape_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_observations")),
        sa.UniqueConstraint(
            "listing_id", "run_id", name=op.f("uq_listing_observations_listing_id_run_id")
        ),
    )
    op.create_index(
        "ix_listing_observations_listing_observed",
        "listing_observations",
        ["listing_id", sa.literal_column("observed_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_listing_observations_run_price",
        "listing_observations",
        ["run_id", "price_czk"],
        unique=False,
        postgresql_where=sa.text("price_czk IS NOT NULL"),
    )
    op.create_table(
        "user_listing_data",
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("private_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_user_listing_data_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("listing_id", name=op.f("pk_user_listing_data")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_listing_data")
    op.drop_index(
        "ix_listing_observations_run_price",
        table_name="listing_observations",
        postgresql_where=sa.text("price_czk IS NOT NULL"),
    )
    op.drop_index("ix_listing_observations_listing_observed", table_name="listing_observations")
    op.drop_table("listing_observations")
    op.drop_index("ix_listing_images_listing_position", table_name="listing_images")
    op.drop_table("listing_images")
    op.drop_index("ix_listing_events_type_occurred", table_name="listing_events")
    op.drop_index("ix_listing_events_listing_occurred", table_name="listing_events")
    op.drop_table("listing_events")
    op.drop_index("ix_listing_distances_reference_road", table_name="listing_distances")
    op.drop_index("ix_listing_distances_listing_calculated", table_name="listing_distances")
    op.drop_table("listing_distances")
    op.drop_index("ix_scrape_runs_status_started_at", table_name="scrape_runs")
    op.drop_index("ix_scrape_runs_started_at", table_name="scrape_runs")
    op.drop_table("scrape_runs")
    op.drop_index(
        "ix_listings_active_usable_area",
        table_name="listings",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(
        "ix_listings_active_price", table_name="listings", postgresql_where=sa.text("is_active")
    )
    op.drop_index("ix_listings_active_last_seen", table_name="listings")
    op.drop_index(
        "ix_listings_active_land_area", table_name="listings", postgresql_where=sa.text("is_active")
    )
    op.drop_index(
        "ix_listings_active_kind_region_district",
        table_name="listings",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(
        "ix_listings_active_derived_price_per_sqm",
        table_name="listings",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("listings")
    for enum_name in (
        "image_archive_status",
        "listing_event_type",
        "scrape_run_status",
        "scrape_run_trigger",
        "listing_kind",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
